CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipient_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  type ENUM('LEAVE_APPLIED','LEAVE_APPROVED','LEAVE_REJECTED','REVIEW_SUBMITTED','REVIEW_FEEDBACK') NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  reference_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
