server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-employee-service
          uri: lb://auth-employee-service
          predicates:
            - Path=/api/auth/**, /api/employees/**, /api/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: leave-performance-service
          uri: lb://leave-performance-service
          predicates:
            - Path=/api/leaves/**, /api/performance/**, /api/goals/**, /api/manager/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
